pipeline:
  name: LLM Framework
  identifier: LLM_Framework
  projectIdentifier: Nic_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: LLM Playground
        identifier: LLM_Playground
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: OpenAI Completion
                  identifier: OpenAI_Completion
                  template:
                    templateRef: OpenAI_Completion
                    versionLabel: 0.1.0
                    gitBranch: master
                    templateInputs:
                      type: Container
                      spec:
                        envVariables:
                          PROMPT: <+input>
              - step:
                  type: JiraCreate
                  name: JiraCreate
                  identifier: JiraCreate
                  spec:
                    connectorRef: account.Harness_JIRA
                    projectKey: HD
                    issueType: Story
                    fields:
                      - name: Description
                        value: "OpenAI Response: <+pipeline.stages.LLM_Playground.spec.execution.steps.OpenAI_Completion.ContainerStep.output.outputVariables.RESPONSE>"
                      - name: Summary
                        value: "OpenAI Prompt: <+pipeline.stages.LLM_Playground.spec.execution.steps.OpenAI_Completion.ContainerStep.spec.envVariables.PROMPT>"
                  timeout: 10m
        tags: {}
